Repository convoyinteractive/payload, pull requests merged in 2020-10, with the labels that each got.

#31 Update "Architects Finest" case
  collections/de/referenzen/architects-finest.yml
Labels: missing assets

#43 Update jobs
  collections/de/jobs.yml
  collections/de/jobs/frontend-developer-junior.yml
  collections/de/jobs/user-interface-design-praktikant.yml
  collections/de/jobs/user-interface-designer.yml
Labels: needs review

#32 Update "Ooigo" case
  assets/corona-ooigo.json
  assets/ooigo-corona.json
  collections/de/referenzen/ooigo.yml
Labels: needs review

#59 POC: Video within jobs gallery
  collections/de/jobs.yml
Labels: Proof of concept, needs review

#58 Add jobs gallery
  collections/de/jobs.yml
Labels: missing assets
