Repository convoyinteractive/payload, pull requests merged in 2021-01, with the labels that each got.

#35 Add the showreel
  collections/de/home.yml
  collections/en/home.yml
Labels: missing assets

#63 Add article "James Arthur Relaunch"
  collections/de/news/2020-01-15.james-arthur-website-relaunch.yml
  collections/en/news/2020-01-15.james-arthur-website-relaunch.yml
Labels: blog

#115 Add article "Oyster Studios Interim Website"
  collections/de/news/2020-08-01.oyster-studios-landingpage.yml
  collections/en/news/2020-08-01.oyster-studios-landingpage.yml
Labels: blog

#117 Add article "Florian Tessloff Rebranding & Relaunch"
  collections/de/news/2021-01-01.florian-tessloff-rebranding
  collections/en/news/2021-01-01.florian-tessloff-rebranding
Labels: blog

#119 Add article "Florian Tessloff Rebranding + Relaunch"
  collections/de/news/2021-01-01.florian-tessloff-rebranding.yml
  collections/en/news/2021-01-01.florian-tessloff-rebranding.yml
Labels: blog

#120 Update article "Florian Tessloff Rebranding"
  assets/florian-tessloff-logo.json
  collections/de/news/2021-01-01.florian-tessloff-rebranding.yml
  collections/en/news/2021-01-01.florian-tessloff-rebranding.yml
Labels: blog, lottie

#134 Update "Florian Tessloff Rebranding" article
  collections/de/news/2021-01-01.florian-tessloff-rebranding.yml
  collections/en/news/2021-01-01.florian-tessloff-rebranding.yml
Labels: blog

#132 Update "Oyster Studios Landingpage" article
  collections/de/news/2020-08-01.oyster-studios-landingpage.yml
  collections/en/news/2020-08-01.oyster-studios-landingpage.yml
Labels: blog

#131 Update "James Arthur Website Relaunch" article
  collections/de/news/2020-01-15.james-arthur-website-relaunch.yml
  collections/en/news/2020-01-15.james-arthur-website-relaunch.yml
Labels: blog

#135 Update "Oyster Studios Landingpage" article
  collections/de/news/2020-08-01.oyster-studios-landingpage.yml
  collections/en/news/2020-08-01.oyster-studios-landingpage.yml
Labels: blog

#136 Update "Florian Tessloff Rebranding" article
  collections/de/news/2021-01-01.florian-tessloff-rebranding.yml
  collections/en/news/2021-01-01.florian-tessloff-rebranding.yml
Labels: blog

#137 Update "James Arthur Website Relaunch" article
  collections/de/news/2020-01-15.james-arthur-website-relaunch.yml
  collections/en/news/2020-01-15.james-arthur-website-relaunch.yml
Labels: blog
